TEAMS = {
	"Buffalo Bills",
	"Miami Dolphins",
	"New England Patriots",
	"New York Jets",
	"Baltimore Ravens",
	"Cincinnati Bengals",
	"Cleveland Browns",
	"Pittsburgh Steelers",
	"Houston Texans",
	"Indianapolis Colts",
	"Jacksonville Jaguars",
	"Tennessee Titans",
	"Denver Broncos",
	"Kansas City Chiefs",
	"Oakland Raiders",
	"San Diego Chargers",
	"Dallas Cowboys",
	"New York Giants",
	"Philadelphia Eagles",
	"Washington Redskins",
	"Chicago Bears",
	"Detroit Lions",
	"Green Bay Packers",
	"Minnesota Vikings",
	"Atlanta Falcons",
	"Carolina Panthers",
	"New Orleans Saints",
	"Tampa Bay Buccaneers",
	"Arizona Cardinals",
	"St. Louis Rams",
	"San Francisco 49ers",
	"Seattle Seahawks",
}

MATCHUPS = [
	("Atlanta Falcons", "Tampa Bay Buccaneers"),
	("Dallas Cowboys", "Jacksonville Jaguars"),
	("Kansas City Chiefs", "Buffalo Bills"),
	("Detroit Lions", "Miami Dolphins"),
	("New York Jets", "Pittsburgh Steelers"),
	("San Francisco 49ers", "New Orleans Saints"),
	("Baltimore Ravens", "Tennessee Titans"),
	("Cleveland Browns", "Cincinnati Bengals"),
	("Indianapolis Colts", "New York Giants"),
	("Pittsburgh Steelers", "Baltimore Ravens"),
	("New England Patriots", "Denver Broncos"),
	("Seattle Seahawks", "Oakland Raiders"),
	("St. Louis Rams", "San Francisco 49ers"),
	("Arizona Cardinals", "Dallas Cowboys"),
	("Cincinnati Bengals", "Jacksonville Jaguars"),
	("Kansas City Chiefs", "New York Jets"),
	("Philadelphia Eagles", "Houston Texans"),
	("Miami Dolphins", "San Diego Chargers"),
	("Cleveland Browns", "Tampa Bay Buccaneers"),
	("Minnesota Vikings", "Washington Redskins"),
	("New Orleans Saints", "Carolina Panthers"),
	("Washington Redskins", "Dallas Cowboys"),
	("New Orleans Saints", "Green Bay Packers"),
	("Pittsburgh Steelers", "Indianapolis Colts"),
	("Cleveland Browns", "Oakland Raiders"),
	("Arizona Cardinals", "Philadelphia Eagles"),
	("Cincinnati Bengals", "Baltimore Ravens"),
	("Buffalo Bills", "New York Jets"),
	("New England Patriots", "Chicago Bears"),
	("Houston Texans", "Tennessee Titans"),
	("Miami Dolphins", "Jacksonville Jaguars"),
	("Minnesota Vikings", "Tampa Bay Buccaneers"),
	("Seattle Seahawks", "Carolina Panthers"),
	("Kansas City Chiefs", "St. Louis Rams"),
	("Detroit Lions", "Atlanta Falcons"),
	("Denver Broncos", "San Diego Chargers"),
	("Pittsburgh Steelers", "Houston Texans"),
	("Denver Broncos", "San Francisco 49ers"),
	("Arizona Cardinals", "Oakland Raiders"),
	("Dallas Cowboys", "New York Giants"),
	("Kansas City Chiefs", "San Diego Chargers"),
	("Baltimore Ravens", "Atlanta Falcons"),
	("Green Bay Packers", "Carolina Panthers"),
	("Indianapolis Colts", "Cincinnati Bengals"),
	("Jacksonville Jaguars", "Cleveland Browns"),
	("Miami Dolphins", "Chicago Bears"),
	("Buffalo Bills", "Minnesota Vikings"),
	("Detroit Lions", "New Orleans Saints"),
	("St. Louis Rams", "Seattle Seahawks"),
	("Washington Redskins", "Tennessee Titans"),
	("New England Patriots", "New York Jets"),
	("San Francisco 49ers", "St. Louis Rams"),
	("Philadelphia Eagles", "New York Giants"),
	("Chicago Bears", "Atlanta Falcons"),
	("Dallas Cowboys", "Seattle Seahawks"),
	("Arizona Cardinals", "Washington Redskins"),
	("San Diego Chargers", "Oakland Raiders"),
	("Baltimore Ravens", "Tampa Bay Buccaneers"),
	("Denver Broncos", "New York Jets"),
	("Detroit Lions", "Minnesota Vikings"),
	("Green Bay Packers", "Miami Dolphins"),
	("Tennessee Titans", "Jacksonville Jaguars"),
	("New England Patriots", "Buffalo Bills"),
	("Cleveland Browns", "Pittsburgh Steelers"),
	("Indianapolis Colts", "Houston Texans"),
	("Seattle Seahawks", "Washington Redskins"),
	("New England Patriots", "Cincinnati Bengals"),
	("San Francisco 49ers", "Kansas City Chiefs"),
	("San Diego Chargers", "New York Jets"),
	("Denver Broncos", "Arizona Cardinals"),
	("New York Giants", "Atlanta Falcons"),
	("Indianapolis Colts", "Baltimore Ravens"),
	("Buffalo Bills", "Detroit Lions"),
	("Carolina Panthers", "Chicago Bears"),
	("Cleveland Browns", "Tennessee Titans"),
	("Dallas Cowboys", "Houston Texans"),
	("Pittsburgh Steelers", "Jacksonville Jaguars"),
	("Philadelphia Eagles", "St. Louis Rams"),
	("New Orleans Saints", "Tampa Bay Buccaneers"),
	("Green Bay Packers", "Minnesota Vikings"),
	("Kansas City Chiefs", "New England Patriots"),
	("Dallas Cowboys", "New Orleans Saints"),
	("Minnesota Vikings", "Atlanta Falcons"),
	("San Francisco 49ers", "Philadelphia Eagles"),
	("San Diego Chargers", "Jacksonville Jaguars"),
	("Houston Texans", "Buffalo Bills"),
	("Baltimore Ravens", "Carolina Panthers"),
	("Detroit Lions", "New York Jets"),
	("Green Bay Packers", "Chicago Bears"),
	("Miami Dolphins", "Oakland Raiders"),
	("Tampa Bay Buccaneers", "Pittsburgh Steelers"),
	("Indianapolis Colts", "Tennessee Titans"),
	("New York Giants", "Washington Redskins"),
	("Chicago Bears", "New York Jets"),
	("Pittsburgh Steelers", "Carolina Panthers"),
	("Seattle Seahawks", "Denver Broncos"),
	("Kansas City Chiefs", "Miami Dolphins"),
	("Arizona Cardinals", "San Francisco 49ers"),
	("Baltimore Ravens", "Cleveland Browns"),
	("Dallas Cowboys", "St. Louis Rams"),
	("Detroit Lions", "Green Bay Packers"),
	("New York Giants", "Houston Texans"),
	("Indianapolis Colts", "Jacksonville Jaguars"),
	("New Orleans Saints", "Minnesota Vikings"),
	("New England Patriots", "Oakland Raiders"),
	("San Diego Chargers", "Buffalo Bills"),
	("Cincinnati Bengals", "Tennessee Titans"),
	("Philadelphia Eagles", "Washington Redskins"),
	("Atlanta Falcons", "Tampa Bay Buccaneers"),
	("Philadelphia Eagles", "Indianapolis Colts"),
	("Chicago Bears", "San Francisco 49ers"),
	("Houston Texans", "Oakland Raiders"),
	("Denver Broncos", "Kansas City Chiefs"),
	("Green Bay Packers", "New York Jets"),
	("San Diego Chargers", "Seattle Seahawks"),
	("St. Louis Rams", "Tampa Bay Buccaneers"),
	("Arizona Cardinals", "New York Giants"),
	("Cincinnati Bengals", "Atlanta Falcons"),
	("Dallas Cowboys", "Tennessee Titans"),
	("Carolina Panthers", "Detroit Lions"),
	("Washington Redskins", "Jacksonville Jaguars"),
	("Buffalo Bills", "Miami Dolphins"),
	("New England Patriots", "Minnesota Vikings"),
	("Cleveland Browns", "New Orleans Saints"),
	("Baltimore Ravens", "Pittsburgh Steelers"),
	("Arizona Cardinals", "San Diego Chargers"),
	("Detroit Lions", "New York Giants"),
	("Denver Broncos", "Indianapolis Colts"),
	("Carolina Panthers", "Tampa Bay Buccaneers"),
	("San Francisco 49ers", "Dallas Cowboys"),
	("Buffalo Bills", "Chicago Bears"),
	("Cincinnati Bengals", "Baltimore Ravens"),
	("Pittsburgh Steelers", "Cleveland Browns"),
	("Philadelphia Eagles", "Jacksonville Jaguars"),
	("Minnesota Vikings", "St. Louis Rams"),
	("Miami Dolphins", "New England Patriots"),
	("Atlanta Falcons", "New Orleans Saints"),
	("New York Jets", "Oakland Raiders"),
	("Tennessee Titans", "Kansas City Chiefs"),
	("Houston Texans", "Washington Redskins"),
	("Seattle Seahawks", "Green Bay Packers"),
]
